# Tugas Pengolahan Citra Digital

Nama : Tuhu Pangestu  
NIM : 230411100096  
Matakuliah : Pengolahan Citra

## Representasi Citra 

Di bagian ini, kita akan merepresentasikan sebuah citra (foto diri) secara digital. Sesuai dengan materi Bab 2, citra digital dapat dianggap sebagai fungsi:  
  
$ f(x,y)f(x,y) $  
$ f(x,y) $ 
  
yang direpresentasikan dalam bentuk matriks berukuran **N baris** dan **M kolom**. Setiap elemen matriks atau **piksel** memiliki nilai intensitas (derajat keabuan).

Implementasi kode

In [ ]:
# Library yang digunakan
from PIL import Image 
from numpy import asarray
import cv2 
import numpy as np


In [ ]:
img = Image.open("gambar.webp")

print(img.format)
print(img.size)
print(img.mode)

WEBP
(800, 534)
RGB


In [ ]:
data = asarray(img)
print(data)

[[[233 233 233]
  [233 233 233]
  [233 233 233]
  ...
  [181 206 218]
  [181 206 218]
  [181 206 218]]

 [[233 233 233]
  [233 233 233]
  [233 233 233]
  ...
  [181 206 218]
  [181 206 218]
  [181 206 218]]

 [[233 233 233]
  [233 233 233]
  [233 233 233]
  ...
  [181 206 218]
  [181 206 218]
  [181 206 218]]

 ...

 [[146 166 180]
  [146 166 180]
  [146 166 180]
  ...
  [103  50  54]
  [102  48  48]
  [107  53  51]]

 [[146 166 182]
  [146 166 182]
  [146 166 182]
  ...
  [107  54  58]
  [105  50  50]
  [107  53  51]]

 [[146 166 182]
  [146 166 182]
  [146 166 182]
  ...
  [109  56  60]
  [106  51  51]
  [107  53  51]]]


# Operasi Dasar Citra

Pada bagian ini, dilakukan implementasi 5 jenis operasi dasar pada citra. Operasi-operasi ini termasuk dalam kategori Aras Titik (pointwise), di mana modifikasi dilakukan pada setiap piksel secara individual.

Operasi 1: Pencerahan Citra (Image Brightening)

In [ ]:
def adjust_brightnes(image_path, beta):
    image = cv2.imread(image_path)
    if image is None:
        print("Error: Image not found.")
        return

    # Adjust brightness
    adjusted = cv2.convertScaleAbs(image, alpha=1, beta=beta)
    cv2.imshow('Original Image',image)
    cv2.imshow('Brightness Adjusted', adjusted)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

image_path = "gambar.webp"
brightness_value = 50
adjust_brightnes(image_path, brightness_value)

Operasi 2: Operasi Negatif (Negative Image)

In [ ]:
def clipping(intensitas):
    if intensitas < 0:
        return 0
    if intensitas > 255:
        return 255
    return intensitas

def atur_pencerahan(nilai_pencerahan, nama_setelah_disave):
    CITRA = Image.open('gambar.webp')
    PIXEL = CITRA.load()

    ukuran_horizontal = CITRA.size[0]
    ukuran_vertikal = CITRA.size[1]

    for x in range(ukuran_horizontal):
        for y in range(ukuran_vertikal):
            R = clipping(PIXEL[x,y][0] + nilai_pencerahan)
            G = clipping(PIXEL[x,y][1] + nilai_pencerahan)
            B = clipping(PIXEL[x,y][2] + nilai_pencerahan)
            PIXEL[x,y] = (R, G, B)

    CITRA.save(nama_setelah_disave)

atur_pencerahan(80,'gambar_setelah_ditingkatkan.jpg')
atur_pencerahan(-80,'gambar_setelah_dikurangi.jpg')

Operasi 3: Pengambangan (Thresholding)

In [ ]:
def thresholding(image_array, threshold):
    # Buat array baru untuk hasil threshold
    result = np.where(image_array > threshold, 255, 0)
    # Jika gambar RGB, lakukan thresholding pada setiap channel
    if len(result.shape) == 3:
        result = result.astype(np.uint8)
    else:
        result = result.astype(np.uint8)
    # Konversi kembali ke gambar PIL
    img_threshold = Image.fromarray(result)
    img_threshold.save("gambar_threshold.webp")
    img_threshold.show()

# Contoh penggunaan
threshold_value = 128
thresholding(data, threshold_value)

Operasi 4: Penskalaan Citra (Image Zooming)

In [ ]:
def translasi(m, n):
    CITRA = Image.open('gambar.webp')
    PIXEL = CITRA.load()

    ukuran_horizontal = CITRA.size[0]
    ukuran_vertikal = CITRA.size[1]

    CITRA_BARU = Image.new("RGB", (ukuran_horizontal, ukuran_vertikal))
    PIXEL_BARU = CITRA_BARU.load()

    start_m = m
    start_n = n

    for x in range(ukuran_horizontal):
        for y in range(ukuran_vertikal):
            x_baru = x + m
            y_baru = y - n

            if(x_baru >= ukuran_horizontal or y_baru >= ukuran_vertikal or x_baru < 0 or y_baru < 0):
                PIXEL_BARU[x,y] = (0,0,0)
            else:
                PIXEL_BARU[x,y] = PIXEL[x_baru,y_baru]

    nama_setelah_disave = "gambar_translasi" + str(m) + "_" + str(n) + ".webp"
    CITRA_BARU.save(nama_setelah_disave)

translasi(50, 50)
translasi(-50, -50)

Operasi 5: Flipping (Pencerminan)

In [ ]:
def flipping(image_path, mode='horizontal'):
    img = Image.open(image_path)
    if mode == 'horizontal':
        flipped_img = img.transpose(Image.FLIP_LEFT_RIGHT)
    elif mode == 'vertical':
        flipped_img = img.transpose(Image.FLIP_TOP_BOTTOM)
    else:
        print("Mode harus 'horizontal' atau 'vertical'")
        return
    flipped_img.save(f"gambar_flipped_{mode}.webp")
    flipped_img.show()

# Contoh penggunaan
flipping(image_path, mode='horizontal')
flipping(image_path, mode='vertical')